### PR TITLE
SA-69684 sbt version from 1.3.13 to 1.8.0 + scala version from 2.12.12 to 2.12.15

### PR DESCRIPTION
**Pull request by adrianmatwiejuk**

### CODE REVIEW

**Comment by iwanek9ld** [comment]
@adrianmatwiejuk 

I think we should test it with `bigdata` and other repositories.

Could you use `publishLocal` to create local version from this PR commit and check how it works with other repostiories?

**Comment by iwanek9ld** [comment]
@zak-dd @yudshimbo @mkulka-9ld-bd 

We would like to bump sbt and scala version in this repository. This is part of fixing vulnerability issue of `sbt`: https://ramencloud.atlassian.net/browse/SA-69188

**Comment by adrianmatwiejuk** [comment]
> Could you use `publishLocal` to create local version from this PR commit and check how it works with other repostiories?
tested dotdata-core (works), bigdata (works but requires bumping wartremover from 2.4.11 to 2.4.15) and sealed-instances-macro (works after commit https://github.com/ramencloud/sbt-config/pull/58/commits/a7059b47df49505c3515d1b9e23d8dcb4a27c3a2)

there probably will be more issues with some of the other repos, maybe this can just hang and i'll continue testing with 
publishLocal

**Comment by adrianmatwiejuk** [comment]
tested with all related web repos, this is ready for review @iwanek9ld

**Review by iwanek9ld — APPROVED** [review]
LGTM

**Pull request merged**
