### PR TITLE
Skip publishing altogether when publishingEnabled = false

### PR DESCRIPTION
**Pull request by zak-dd**
This PR replaces `publishArtifact := false` with `publish / skip := true`. These settings have a different meaning (e.g. even when `publishArtifact` is set to `false`, `publishTo` still must be set). The latter should be used for skipping publishing https://www.scala-sbt.org/1.x/docs/Publishing.html#Skip+publishing

### CODE REVIEW

**Comment by dot-vlad** [comment]
@er1c do you want to weight it? :)

**Review by dot-vlad — APPROVED** [review]
Context: https://github.com/sbt/sbt/issues/3136, looks like more people are in support of `publish / skip`

@zak-dd we will have to check the main project `bigdata` and Core now to make sure it doesn't define neither  `publish / skip` nor `publishArtifact` with the values contradicting the ones here. It will probably be fun to debug what hapens if  `publish / skip` = true and `publishArtifact` = false and vice versa. But this is about bumping versions in these projects, I don't think it blocks this PR.

**Review by dot-vlad — COMMENTED** [review]
@zak-dd, one moment, can you see what they've decided in https://github.com/sbt/sbt/issues/3136, does `publish / skip` affect `publishLocal`, `publishSigned` too?

**Comment by er1c** [comment]
@dot-vlad I already talked to @zak-dd about this, and asked him to replace the `publishArtifact := false` with the `publish / skip`

**Pull request merged**
